services:
  discord-bot:
    image: ghcr.io/jason6537/gmc-discord-bot:${IMAGE_TAG}
    container_name: gmc-bot
    restart: unless-stopped
    init: true

    env_file:
      - .env

    environment:
      DISCORD_API_TOKEN: ${API_TOKEN}


