services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gmc-bot
    restart: unless-stopped
    init: true
    env_file:
      - .env
    environment:
      - DISCORD_API_TOKEN=${API_TOKEN}
      - OTEL_TRACES_EXPORTER=${OTEL_TRACES_EXPORTER}
      - OTEL_METRICS_EXPORTER=${OTEL_METRICS_EXPORTER}
      - OTEL_LOGS_EXPORTER=${OTEL_LOGS_EXPORTER}
      - OTEL_METRIC_EXPORT_INTERVAL=15000
      - OTEL_SERVICE_NAME=discord-bot


